version: "3.9"
services:
  server:
    container_name: server_minimal-1
    build: .
    environment:
      - X509_USER_PROXY=/tmp/cert/x509up_u14057
    volumes:
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/certificates
        target: /etc/grid-security/certificates
      - type: bind
        source: ./certs
        target: /tmp/cert
      - type: bind
        source: ./configs
        target: /xrdconfigs
      - type: bind
        source: ./scripts
        target: /scripts
      - type: bind
        source: ./store
        target: /storage
    ports:
      - "1094:1094"
    networks:
      network1:
        ipv4_address: 10.5.0.5
    tty: true

  proxy:
    container_name: proxy_minimal-1
    build: .
    environment:
      - X509_USER_PROXY=/tmp/cert/x509up_u14057
    volumes:
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/certificates
        target: /etc/grid-security/certificates
      - type: bind
        source: ./certs
        target: /tmp/cert
      - type: bind
        source: ./configs
        target: /xrdconfigs
      - type: bind
        source: ./scripts
        target: /scripts
      - type: bind
        source: ./cache
        target: /cache
    networks:
      network1:
        ipv4_address: 10.5.0.6
    tty: true

  client:
    container_name: client_minimal-1
    build: .
    environment:
      - X509_USER_PROXY=/tmp/cert/x509up_u14057
    volumes:
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/certificates
        target: /etc/grid-security/certificates
      - type: bind
        source: ./certs
        target: /tmp/cert
      - type: bind
        source: ./configs
        target: /xrdconfigs
      - ./configs/client-plugin-proxy.conf:/etc/xrootd/client.plugins.d/client-plugin-proxy.conf
    networks:
      network1:
        ipv4_address: 10.5.0.7
    tty: true

networks:
  network1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
